-- Auto-generated venue seed data from Google Places API
-- Generated: 2026-01-11T13:15:55.998Z
-- Run with: wrangler d1 execute reviews-db --local --file=scripts/seed-venues.sql

INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v056', 'Owl & Pussycat', 'bar', '34 Redchurch St, London E2 7DP', 'Bustling traditional venue with a small outside terrace, pub games and an upstairs dining room.', 'https://www.owlandpussycatshoreditch.com/', 51.52429660000001, -0.0754871, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v057', 'Pizza East - Shoreditch', 'restaurant', '56 Shoreditch High St, London E1 6JJ', 'Pizzeria with industrial looks, serving rustic pizza, antipasti & weekend brunch.', 'https://www.pizzaeast.com/shoreditch?utm_source=gmb&utm_medium=uberall&utm_campaign=business_profile', 51.5238052, -0.0769164, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v058', 'Dishoom Shoreditch', 'cafe', '7 Boundary St, London E2 7JE', 'Buzzy destination for Indian street food in Bombay-style digs with vintage decor & upscale touches.', 'https://www.dishoom.com/shoreditch?utm_source=google&utm_medium=organic&utm_campaign=Yext&utm_content=D2-Shoreditch&y_source=1_MjMwNDkyMDQtNzE1LWxvY2F0aW9uLndlYnNpdGU=', 51.5245002, -0.0765998, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v059', 'TBC', 'bar', '100-106 Leonard St, London EC2A 4RH', 'Eclectic all-day menu plus ping pong and packed calendar of workshops, music and poetry.', 'https://www.wearetbc.com/', 51.5246107, -0.081424, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v060', 'LOUNGE BOHEMIA - by appointment', 'bar', '1e Great Eastern St, London EC2A 3EJ', 'Laid-back cocktail bar with kitschy, living room-style decor, with sofas and paper lamps.', 'http://www.loungebohemia.com/', 51.522844, -0.078126, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v061', 'The Light Bar & Dining', 'bar', '233 Shoreditch High St, London E1 6PJ', 'Converted warehouse with beer garden and roof terrace, Modern European dining and weekend DJs.', 'https://www.lightbarlondon.com/', 51.5221414, -0.07833, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v062', 'The Horse & Groom', 'bar', '28 Curtain Rd, London EC2A 3NZ', 'Rustic yet stylish pub with real ales & a menu of steaks, burgers & updated pub-style grub.', 'https://www.thehorseandgroom.net/', 51.5228778, -0.0804583, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v063', 'The Crown and Shuttle', 'bar', '226 Shoreditch High St, London E1 6PJ', 'Hip, bar with exposed brick and junkyard decor, craft beers and a large garden with food truck.', 'http://crownandshuttle.com/', 51.5224951, -0.07817969999999999, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v064', 'Strongroom Venue', 'bar', '120-124 Curtain Rd, London EC2A 3SQ', 'Modern takes on a pub menu served in a split-level venue with outdoor seating, live bands and DJs.', 'http://www.strongroombar.com/', 51.5259464, -0.08005219999999999, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v065', 'BOXPARK Shoreditch', 'bar', '2-10 Bethnal Grn Rd, London E1 6GY', 'Shipping container, pop-up mall for independent and global, fashion and lifestyle stores and cafes.', 'https://boxpark.co.uk/shoreditch?utm_medium=organic&utm_source=gbp&utm_campaign=homepage', 51.52347229999999, -0.0757539, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v066', 'Barrio - Shoreditch', 'bar', '141-143 Shoreditch High St, London E1 6JE', 'Vibrant destination serving tapas-style food & cocktails, plus late night club with DJs.', 'https://www.barriobars.com/bars/shoreditch?utm_medium=organic&utm_source=gbp&utm_campaign=homepage', 51.5260601, -0.07820909999999999, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v067', 'The Cornershop Bar', 'bar', '123 Shoreditch High St, London E1 6JE', 'Relaxed bar with a tapas-style snack menu, hosting live comedy, open mic sessions and gigs.', 'http://www.thecornershopbar.co.uk/', 51.5270811, -0.0782291, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v068', 'Pret A Manger', 'cafe', '57 Great Eastern St, London EC2A 3QD', 'Counter-serve chain for ready-made sandwiches plus breakfast, coffee, soups & salads.', 'https://www.pret.co.uk/en-GB/shop-finder/l/london/57-great-eastern-street/10185', 51.524587, -0.08116899999999999, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v069', 'Smoking Goat Shoreditch', 'bar', '64 Shoreditch High St, London E1 6JJ', 'Cool, laid-back restaurant serving quirky dishes & drinks inspired by Bangkok’s late-night canteens.', 'http://www.smokinggoatbar.com/', 51.524224, -0.0769238, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v070', 'Boundary Shoreditch', 'bar', '2-4 Boundary St, London E2 7DD', 'Hip rooms & suites in a converted warehouse, offering an upscale restaurant & a chic rooftop bar.', 'https://boundary.london/', 51.524475, -0.0762987, unixepoch());