-- Auto-generated venue seed data from Google Places API
-- Generated: 2026-01-11T13:13:42.839Z
-- Run with: wrangler d1 execute reviews-db --local --file=scripts/seed-venues.sql

INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v040', 'The Chamberlain Hotel, Tower Bridge', 'bar', '132-135 Minories, London EC3N 1NU', 'Victorian-era pub with a Modern British menu, and cosy, stylish guestrooms with air-conditioning.', 'https://www.thechamberlainhotel.co.uk/?partner=8163&utm_source=googlemybusiness&utm_medium=organic&utm_campaign=yext&utm_content=H008%3Futm_source%3Dgooglemybusiness&utm_medium=organic&utm_campaign=yext&utm_content=H008&y_source=1_MTIyMzcwMzAtNzE1LWxvY2F0aW9uLndlYnNpdGU%3D', 51.5122297, -0.0756757, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v041', 'Premier Inn London City (Tower Hill) hotel', 'restaurant', '22-24 Prescot St, London E1 8BB', 'Simple rooms, some with shower only, plus an on-site restaurant/bar and good transport links.', 'https://www.premierinn.com/gb/en/hotels/england/greater-london/london/london-city-tower-hill.html?cid=GLBC_LONCIT', 51.5113183, -0.0716663, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v042', 'The Corner | London City', 'bar', '42 Adler St, London E1 1EE', 'Trendy, unpretentious hotel offering a living room-style lobby and a bright bar serving local fare.', 'https://www.thecornerlondoncity.co.uk/', 51.51619420000001, -0.06768679999999999, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v043', 'So Restaurant', 'restaurant', 'So Restaurant, 5 Middlesex St, London E1 7AA', 'Sushi and modern Japanese cuisine with European touches in a contemporary room with neutral tones.', 'http://www.sorestaurant.com/', 51.5156641, -0.0756868, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v044', 'Barcelona Tapas Bar & Restaurant', 'bar', 'Barcelona Tapas Bar & Restaurant 1 Middlesex Street (OFF St Botolph Street, London EC3A 7DT, London E1 7AA', 'Colourful backdrop of mosaics and original art in Spanish restaurant and bar, part of small chain.', 'http://www.barcelona-tapas.com/', 51.5154196, -0.0755005, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v045', 'The White Hart', 'bar', '89 Whitechapel High St, London E1 7RA', 'Straightforward, traditional watering hole offering Thai and English food and live TV sports.', 'http://www.thewhitehartlondon.co.uk/index', 51.515843, -0.0708425, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v046', 'Slug & Lettuce - Aldgate', 'bar', 'St Claire House, 30-33 Minories, London EC3N 1DD', 'Smart bar chain with a cocktail list, a menu of global classics, and contemporary decor.', 'https://www.slugandlettuce.co.uk/aldgate?utm_source=gmb&utm_medium=organic&utm_campaign=homepage', 51.5123462, -0.07527620000000002, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v047', 'Thai Square Minories', 'bar', '136-138 Minories, London EC3N 1NT', 'Contemporary Thai chain restaurant with bronze Buddhist sculptures & traditional carvings.', 'https://thaisq.com/restaurants/minories/', 51.5123418, -0.07562139999999999, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v048', 'Halal Restaurant', 'restaurant', '2 St Mark St, London E1 8DJ', 'Timeless Indian restaurant with simple menu, in the same home since it was established before WWII.', 'http://www.halalrest.co.uk/', 51.5134536, -0.0715783, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v049', 'Subway', 'restaurant', '75 Aldgate High St, London EC3N 1BD', 'Casual counter-serve chain for build-your-own sandwiches & salads, with health-conscious options.', 'https://restaurants.subway.com/united-kingdom/en/london/75-high-street-35641-0?utm_source=yxt-goog&utm_medium=local&utm_term=acq&utm_content=35641&utm_campaign=evergreen-2020&y_source=1_MTQ5MjQ3NzAtNzE1LWxvY2F0aW9uLndlYnNpdGU%3D', 51.5138032, -0.0755153, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v050', 'The Empress', 'restaurant', '141 Leman St, London E1 8EY', 'Traditional Indian and Bangaldeshi food in a spotlit room with wooden floors and white tablecloths.', 'http://www.theempress.co.uk/', 51.5113339, -0.0685036, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v051', 'Oummi Bon Appetit lebanese', 'restaurant', '133 Leman St, London E1 8EY', 'Lebanese meze and chargrilled meat dishes in small and simple, chrome-furnished restaurant/takeaway.', 'http://www.bonappetitlebanese.com/', 51.5115822, -0.0686907, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v052', 'Satyrio- Italian Restaurant & Wine Merchants', 'restaurant', '49 Aldgate High St, London EC3N 1AL', 'Chill trattoria offering pastas, Italian cheese & charcuterie menus, plus an extensive wine list.', 'https://www.satyrio.co.uk/', 51.5142521, -0.0742536, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v053', 'The Black Horse', 'bar', 'The black horse, 40 Leman St, London E1 8EU', NULL, 'https://blackhorselondoncouk.simplybook.it/', 51.5137627, -0.0707595, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v054', 'Pizza Union Aldgate', 'restaurant', '29 Leman St, London E1 8PT', NULL, 'https://www.pizzaunion.com/#menu', 51.5139055, -0.07030499999999999, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v055', 'Pilpel', 'restaurant', '60 Alie St, Aldgate, London E1 8PX', 'Middle Eastern fast food to take away or eat in a no-nonsense setting with a few seats.', 'http://www.pilpel.co.uk/', 51.5140748, -0.07009449999999999, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v056', 'Treves & Hyde', 'bar', '15/17 Leman St, London E1 8EN', 'Continental-inspired dishes in a modern setting with outdoor tables & classic coffee & bar drinks.', NULL, 51.5147643, -0.0706437, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v057', 'Premier Inn London City (Aldgate) hotel', 'restaurant', '66 Alie St, London E1 8PX', 'Simple hotel offering unfussy rooms with 40-inch flat-screens and Wi-Fi, plus a relaxed restaurant.', 'https://www.premierinn.com/gb/en/hotels/england/greater-london/london/london-city-aldgate.html?cid=GLBC_LONALD', 51.51419019999999, -0.0697005, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v058', 'Costa Coffee', 'cafe', '126 Whitechapel High St, Aldgate, London E1 7PU', 'Counter-service coffee chain offering hot drinks, iced coolers, sweet snacks and sandwiches.', 'https://www.costa.co.uk/?utm_campaign=d998aea6-9610-46d0-81de-a0dc771f9cb5&utm_source=local', 51.515033, -0.072946, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v059', 'Pret A Manger', 'cafe', '1 Commercial St, London E1 6BF', 'Counter-serve chain for ready-made sandwiches plus breakfast, coffee, soups & salads.', 'https://www.pret.co.uk/en-GB/shop-finder/l/london/1-commercial-street/10402', 51.5155828, -0.0728277, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v060', 'Curzon Aldgate', 'bar', '2 Canter Wy, London E1 8PS', NULL, 'https://www.curzon.com/venues/aldgate/', 51.5137742, -0.0690075, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v061', 'Peter''s Cafe London', 'cafe', '73 Aldgate High St, London EC3N 1BD', NULL, NULL, 51.5138691, -0.0754019, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v062', 'Dulce Coffee', 'cafe', '86 Whitechapel High St, London E1 7QX', 'A classic coffee shop drink menu alongside assorted sandwiches & baked goods with outdoor tables.', 'http://www.dulcecoffeeandkitchen.com/', 51.5159021, -0.0705461, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v063', 'Starbucks Coffee', 'cafe', '50 Minories, London EC3N 1JJ', 'Seattle-based coffeehouse chain known for its signature roasts, light bites and WiFi availability.', 'https://www.starbucks.co.uk/store-locator/12153', 51.5116518, -0.07519669999999999, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v064', 'Circle & Slice', 'cafe', '11 Whitechapel Rd, London E1 1DU', NULL, 'https://circleslice.shop/', 51.5164133, -0.069226, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v065', 'Pret A Manger', 'cafe', '85 Aldgate High St, London EC3N 1LH', 'Counter-serve chain for ready-made sandwiches plus breakfast, coffee, soups & salads.', 'https://www.pret.co.uk/en-GB/shop-finder/l/london/85-aldgate-high-street/58', 51.51363, -0.07622999999999999, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v066', 'Pret A Manger', 'cafe', '21 Mansell St, London E1 8AA', 'Counter-serve chain for ready-made sandwiches plus breakfast, coffee, soups & salads.', 'https://www.pret.co.uk/en-GB/shop-finder/l/london/21-mansell-street/10291', 51.51379290000001, -0.0732797, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v067', 'De Vine', 'cafe', '19 Vine st next, under railway bridge, to, 2 America Square, London EC3N 2PX', 'Straightforward counter-serve cafe & deli dishing up informal nibbles for breakfast & lunch.', NULL, 51.5110165, -0.07562819999999999, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v068', 'Pret A Manger', 'cafe', '3 America Square, London EC3N 2LR', 'Counter-serve chain for ready-made sandwiches plus breakfast, coffee, soups & salads.', 'https://www.pret.co.uk/en-GB/shop-finder/l/london/3-america-square/177', 51.51152459999999, -0.0756604, unixepoch());
INSERT INTO venues (id, name, type, address, description, website, latitude, longitude, created_at) VALUES ('v069', 'Exmouth Coffee Company', 'cafe', '83 Whitechapel High St, Algate East, London E1 7QX', 'Buzzy cafe with coffee roasted on-site and bites such as homemade cakes, salads and quiches.', NULL, 51.5160059, -0.0703758, unixepoch());